### ISSUE TITLE
Push to DockerHub

### ISSUE THREAD

**Issue by ADawesomeguy** [LadueCS/OpenContest-Server#23]
Now that we have [a Dockerfile](#21) and a good idea of federation I think we should set up a workflow to push to DockerHub on tag so that people can easily run Docker containers to set up even more servers.

**Comment by Ta180m** [comment]
Sure! We currently also push to PyPI, but Docker/Podman is probably more convenient for most people.

**Comment by ADawesomeguy** [comment]
Yep, I agree with that, I'll get to work on the workflow and close this once I submit the PR.

**Comment by ADawesomeguy** [comment]
Added in #24.
