### ISSUE TITLE
Docker TODO

### ISSUE THREAD

**Issue by ADawesomeguy** [LadueCS/OpenContest-Server#25]
- [ ] We need to figure out a way to either push the README to Docker Hub along with the repo on tag or we can just fill it in manually ourselves.
- [x] Add information regarding adding contests to Docker container (likely just mapping Docker volume to host folder but docs are needed to explain this sort of thing) (Edit: mapping a host volume to the contests directory is confirmed to work) (#27)

**Comment by Ta180m** [comment]
> * [ ]  We need to figure out a way to either push the README to Docker Hub along with the repo on tag or we can just fill it in manually ourselves.
> 
>     * [x]  Add information regarding adding contests to Docker container (likely just mapping Docker volume to host folder but docs are needed to explain this sort of thing) (Edit: mapping a host volume to the contests directory is confirmed to work) ([Update README to include Docker installation and usage info #27](https://github.com/LadueCS/OpenContest-Server/pull/27))

Is the README not updated with each push to the Docker Hub?

**Comment by Ta180m** [comment]
It looks like syncing the README is only available in paid plans, and I honestly don't think it really matters very much, so closing.

**Comment by ADawesomeguy** [comment]
No problem, I can just do it manually.
