### ISSUE TITLE
Add DELETE requests to get rid of users

### ISSUE THREAD

**Issue by ADawesomeguy** [LadueCS/OpenContest-Server#29]
Deleting the whole DB or using the SQLite command isn't really practical, so people should be able to delete their own accounts and some admins or something should be able to delete others' accounts.

**Comment by Ta180m** [comment]
Do you think it would be better to add this to the OpenContest protocol?

**Comment by ADawesomeguy** [comment]
Yep, and then it could be implemented here.

**Comment by ADawesomeguy** [comment]
@Ta180m I was thinking we could also implement some sort of admin key? It could be used for perms to delete or freeze users and be defined through an environment variable possibly. If you think it's okay I'll PR it to OCP.

**Comment by Ta180m** [comment]
Is that necessary though? For deleting users, the admin can do it using SQLite or the user can authenticate with their credentials to do it. We should make OCP as simple as possible while still being useful and usable.

**Comment by Ta180m** [comment]
This has been added to OCP v2.6.0 and the CLI client and I'll be implementing it today in the server too.
